// Standard error codes
module.exports = {
  NOT_FOUND: 'ERR_NOT_FOUND',
  UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  FORBIDDEN: 'ERR_FORBIDDEN',
  BAD_REQUEST: 'ERR_BAD_REQUEST',
  CONFLICT: 'ERR_CONFLICT',
  TIMEOUT: 'ERR_TIMEOUT',
  RATE_LIMITED: 'ERR_RATE_LIMITED',
  VALIDATION_FAILED: 'ERR_VALIDATION_FAILED',
  BLOCKCHAIN_ERROR: 'ERR_BLOCKCHAIN_ERROR',
  SERVICE_UNAVAILABLE: 'ERR_SERVICE_UNAVAILABLE',
  INTERNAL: 'ERR_INTERNAL',
};
